#!/bin/sh

# Function to display error and quit
die() { printf "ERR: %s\n" "$1" >&2 ; exit 1; }
DEFAULT_MACOS_CONFIG="$HOME"/.config/alacritty.toml

if . "${HOME}/.cache/wal/colors.sh"; then
  echo "Wal Colors Script Found!!, exporting..."
else
  die "Wal colors not found, exiting script. Have you executed Wal before?"
fi
READLINK=$( command -v greadlink || command -v readlink )

# Get config file
if [ -n "$1" ]; then
  [ -e "$1" ] || touch "$1" || die "Selected config doesn't exist, exiting script."
  printf "Config found, destination ready.\n"
  CFG=$1
  [ -L "$1" ] && {
    printf "Following symlink to config...\n"
    CFG=$($READLINK -f "$1")
  }
else
  # Default config path in Mac systems
  if [ ! -e "$DEFAULT_MACOS_CONFIG" ]; then
    mkdir -p "$HOME"/.config/alacritty
    touch $DEFAULT_MACOS_CONFIG
    echo "Alacritty config not found, attempting to create..."
  fi

  CFG="$DEFAULT_MACOS_CONFIG"
  [ -L "$DEFAULT_MACOS_CONFIG" ] && {
    printf "Following symlink to config...\n"
    CFG=$($READLINK -f "$DEFAULT_MACOS_CONFIG")
  }
fi

# Create temp file for sed results
tempfile=$(mktemp)
trap 'rm $tempfile' INT TERM EXIT

# Delete existing color declarations generated by this script
# If begin comment exists
if grep -q '^# COLORSCHEME BEGIN ###########' "$CFG"; then
  # And if end comment exists
  if grep -q '^# COLORSCHEME END #############' "$CFG"; then
    # Delete contents of the block
    printf "Existing generated colors found, replacing new colors...\n"
    sed '/^# COLORSCHEME BEGIN ###########/,/^# COLORSCHEME END #############/ {
      /^# COLORSCHEME BEGIN ###########/! { /^# COLORSCHEME END #############/!d; }
    }' "$CFG" > "$tempfile" \
      && cat "$tempfile" > "$CFG"
  # If no end comment, don't do anything
  else
    die "No '# COLORSCHEME END #############' comment found, please ensure it is present."
  fi
# If no begin comment found
else
  # Don't do anything and notify user if there's an end comment in the file
  ! grep -q '^# COLORSCHEME END #############' "$CFG" || die "Found '# COLORSCHEME END #############' comment, but no '# COLORSCHEME BEGIN ###########' comment found. Please ensure it is present."
  printf "There's no existing 'generated' colors, adding comments...\n";
  printf '# COLORSCHEME BEGIN ###########\n# COLORSCHEME END #############' >> "$CFG";
fi

# Write new color definitions
# We know $colorX is unset, we set it by sourcing above
# shellcheck disable=SC2154
{ sed "/^# COLORSCHEME BEGIN ###########/ r /dev/stdin" "$CFG" > "$tempfile" <<EOF
							  #
[colors.primary]			  #
background = '$color0'		  #		
foreground = '$color15'		  #
							  #
[colors.cursor]				  #
text   = '$color0'			  #
cursor = '$color7'			  #
							  #
[colors.vi_mode_cursor]		  #
text    = '$color0'			  #
cursor  = '$color15'		  #
							  #
[colors.search.matches]		  #
foreground = '$color0'		  #
background = '$color15'		  #
							  #
[colors.search.focused_match] #
foreground = 'CellBackground' #
background = 'CellForeground' #
							  #
[colors.line_indicator]		  #
foreground = 'None'			  #
background = 'None'			  #
							  #
[colors.footer_bar]			  #
foreground = '$color15'		  #
background = '$color7'	      #
							  #
[colors.selection]			  #
text       = 'CellBackground' #
background = 'CellForeground' #
							  #
[colors.normal]				  #
black   = '$color0'			  #
red     = '$color1'			  #
green   = '$color2'			  #
yellow  = '$color3'			  #
blue    = '$color4'			  #
magenta = '$color5'			  #
cyan    = '$color6'			  #
white   = '$color7'			  #
							  #
[colors.bright]				  #
black   = '$color8'			  #
red     = '$color9'			  #
green   = '$color10'		  #
yellow  = '$color11'		  #
blue    = '$color12'		  #
magenta = '$color13'		  #
cyan    = '$color14'		  #
white   = '$color15'		  #
                              #
EOF
} && cat "$tempfile" > "$CFG" \
  && rm "$tempfile"
trap - INT TERM EXIT
echo "Colorscheme Is Applied!!"
