[FileDialog]
history=file:///home/aKqir24/Documents/lmms/plugins/VST/Monster, file:///home/aKqir24/Documents/lmms/plugins/VST/QuietMusic/Quiet Piano 2 Lite, file:///home/aKqir24/Documents/lmms/plugins/VST/Bitsonic/Keyzone Classic, file:///home/aKqir24/Documents/lmms/projects, file:///home/aKqir24/Documents/lmms/plugins/VST/QuietMusic/Love Lofi 2 Lite/LOVE-FI 2 LITE 2.0.0 VST WIN 64 BIT, file:///home/aKqir24/Documents/lmms/plugins/VST/QuietMusic/Classic Guitar 1 Lite/CLASSIC GTR LITE 1.6.0 VST WIN 64 BIT/CLASSIC GTR LITE 1.6.0 VST WIN 64 BIT
lastVisited=file:///home/aKqir24/Documents/lmms/plugins/VST/QuietMusic/Classic Guitar 1 Lite/CLASSIC GTR LITE 1.6.0 VST WIN 64 BIT/CLASSIC GTR LITE 1.6.0 VST WIN 64 BIT
qtVersion=5.15.3
shortcuts=file:///home/aKqir24/Desktop, file:///home/aKqir24/Downloads, file:///home/aKqir24/Music, file:///home/aKqir24/Documents/lmms, file:///, file:///home
sidebarWidth=270
treeViewHeader="@ByteArray(\0\0\0\xff\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x2\x86\0\0\0\x4\x1\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x64\xff\xff\xff\xff\0\0\0\x81\0\0\0\0\0\0\0\x4\0\0\0\xf5\0\0\0\x1\0\0\0\0\0\0\0\xee\0\0\0\x1\0\0\0\0\0\0\0=\0\0\0\x1\0\0\0\0\0\0\0\x66\0\0\0\x1\0\0\0\0\0\0\x3\xe8\0\xff\xff\xff\xff)"
viewMode=Detail

[Qt]
customColors\0=4291869869
customColors\1=4294967295
customColors\10=4294967295
customColors\11=4294967295
customColors\12=4294967295
customColors\13=4294967295
customColors\14=4294967295
customColors\15=4294967295
customColors\2=4294967295
customColors\3=4294967295
customColors\4=4294967295
customColors\5=4294967295
customColors\6=4294967295
customColors\7=4294967295
customColors\8=4294967295
customColors\9=4294967295
