# -*- conf -*-

letter-spacing=0
vertical-letter-offset=0
horizontal-letter-offset=0
font=EnvyCodeR Nerd Font Mono:style=Regular:size=10
font-italic=EnvyCodeR Nerd Font:style=Italic:size=10
font-size-adjustment=0.5

pad=8x6
resize-by-cells=yes
resize-keep-grid=yes
resize-delay-ms=100
bold-text-in-bright=yes
initial-window-size-pixels=700x500  # Or,
word-delimiters=,│`|:"'()[]{}<>
initial-window-mode=windowed

[environment]
name=value

[bell]
system=yes
urgent=no
notify=no
visual=no

[desktop-notifications]
command=notify-send --wait --app-name ${app-id} --icon ${app-id} --category ${category} --urgency ${urgency} --expire-time ${expire-time} --hint STRING:image-path:${icon} --hint BOOLEAN:suppress-sound:${muted} --hint STRING:sound-name:${sound-name} --replace-id ${replace-id} ${action-argument} --print-id -- ${title} ${body}
command-action-argument=--action ${action-name}=${action-label}
inhibit-when-focused=yes

[scrollback]
lines=1000
multiplier=3.0
indicator-position=relative
indicator-format=""

[url]
launch=xdg-open ${url}
label-letters=sadfjklewcmpgh
osc8-underline=url-mode
regex=(((https?://|mailto:|ftp://|file:|ssh:|ssh://|git://|tel:|magnet:|ipfs://|ipns://|gemini://|gopher://|news:)|www\.)([0-9a-zA-Z:/?#@!$&*+,;=.~_%^\-]+|\([]\["0-9a-zA-Z:/?#@!$&'*+,;=.~_%^\-]*\)|\[[\(\)"0-9a-zA-Z:/?#@!$&'*+,;=.~_%^\-]*\]|"[]\[\(\)0-9a-zA-Z:/?#@!$&'*+,;=.~_%^\-]*"|'[]\[\(\)0-9a-zA-Z:/?#@!$&*+,;=.~_%^\-]*')+([0-9a-zA-Z/#@$&*+=~_%^\-]|\([]\["0-9a-zA-Z:/?#@!$&'*+,;=.~_%^\-]*\)|\[[\(\)"0-9a-zA-Z:/?#@!$&'*+,;=.~_%^\-]*\]|"[]\[\(\)0-9a-zA-Z:/?#@!$&'*+,;=.~_%^\-]*"|'[]\[\(\)0-9a-zA-Z:/?#@!$&*+,;=.~_%^\-]*'))

[cursor]
style=beam
blink=yes
blink-rate=500
beam-thickness=1

[mouse]
hide-when-typing=yes
alternate-scroll-mode=yes

[touch]
long-press-delay=400

[colors]
alpha=1.0
alpha-mode=default 
background=0c192a
foreground=77e2ea
flash=8d6f31
flash-alpha=0.5

# Normal/regular colors (color palette 0-7)
regular0=0c192a  # black
regular1=8d6f31  # red
regular2=d7b454  # green
regular3=067885  # yellow
regular4=0d8d93  # blue
regular5=25a2a0  # magenta
regular6=5eb9a2  # cyan
regular7=539ea3  # white

# Bright colors (color palette 8-15)
bright0=073747   # bright black
bright1=8d6f31   # bright red
bright2=e8c76a   # bright green
bright3=0b7d87   # bright yellow
bright4=0d8d93   # bright blue
bright5=25a2a0   # bright magenta
bright6=5eb9a2   # bright cyan
bright7=77e2ea   # bright white

## Misc colors
# selection-foreground=<inverse foreground/background>
# selection-background=<inverse foreground/background>
# jump-labels=<regular0> <regular3>          # black-on-yellow
# scrollback-indicator=<regular0> <bright4>  # black-on-bright-blue
# search-box-no-match=<regular0> <regular1>  # black-on-red
# search-box-match=<regular0> <regular3>     # black-on-yellow
# urls=<regular3>
