[DEFAULT]
fetch-updates-in-background = no

[app.df8a8ce2825716efdba1cf0564262ac4]
website = 
name = QDiskInfo
file_path = /home/aKqir24/Desktop/.AppImages/qdiskinfo.appimage

[app.6301ce752daee36b11499ef1311b263f]
website = 
name = Tenacity
file_path = /home/aKqir24/Desktop/.AppImages/tenacity.appimage

[app.f6be7bd2a9b7b65f95ec7293865a13c5]
website = 
name = GNU Image Manipulation Program
file_path = /home/aKqir24/Desktop/.AppImages/gnu_image_manipulation_program.appimage

[app.064add5a9a66fe09f59297b34c407973]
website = 
name = rustdesk
file_path = /home/aKqir24/Desktop/.AppImages/rustdesk.appimage

[app.6d64ad7341162f9632525e4547ffc350]
name = drawio
file_path = /home/aKqir24/Desktop/.AppImages/drawio.appimage

[app.6d64ad7341162f9632525e4547ffc350.update_manager]

[app.51e449bbebf17c9d8f2c09d9daa4fd60]
name = figma-linux
file_path = /home/aKqir24/Desktop/.AppImages/figmalinux.appimage

[app.18ce90a19a14b740e84f2ebdab623b4d]
name = LibreOffice
file_path = /home/aKqir24/Desktop/.AppImages/libreoffice.appimage

[app.48ee3ade1ae784398deab4e186afc88e]
name = Figma
file_path = /home/aKqir24/Desktop/.AppImages/figma.appimage

[app.6301ce752daee36b11499ef1311b263f.update_manager]

[app.92283a468bc3c0d580f78fc9b730f129]
name = Shotcut
file_path = /home/aKqir24/Desktop/.AppImages/shotcut.appimage

[app.92283a468bc3c0d580f78fc9b730f129.update_manager]

[app.698c9c0284496d3493a2682f08767582]
name = Inkscape
file_path = /home/aKqir24/Desktop/.AppImages/inkscape.appimage

[app.48ee3ade1ae784398deab4e186afc88e.update_manager]

[app.8030619b23f9d6c0cd5b721cb2cc5552]
name = LMMS
file_path = /home/aKqir24/Desktop/.AppImages/lmms.appimage

[app.18ce90a19a14b740e84f2ebdab623b4d.update_manager]

[app.c5ca6bd4706235fc60951d048598c0cf]
name = Helium
file_path = /home/aKqir24/Desktop/.AppImages/helium.appimage

[app.c5ca6bd4706235fc60951d048598c0cf.update_manager]

[app.f6be7bd2a9b7b65f95ec7293865a13c5.update_manager]

[app.47779e41083974aef6aae02ce605572e]
name = VSCodium
file_path = /home/aKqir24/Desktop/.AppImages/vscodium.appimage

[app.2d5a42bdb34c61b117c2a24c7c024a6f]
name = OpenCode
file_path = /home/aKqir24/AppImages/opencode.appimage

[app.2d5a42bdb34c61b117c2a24c7c024a6f.update_manager]

[app.5c45e807d8262135655f0d620ba31abd]
name = OpenCode
file_path = /home/aKqir24/Desktop/.AppImages/opencode.appimage_1_18_3.appimage

