backend = "egl"
vsync = true
sw-opti = false
use-damage = false
frame-pacing = true
xrender-sync-fence = true
unredir-if-possible = false
glx-copy-from-font = false

corner-radius = 16
round-borders = 16
paint-on-overlay = true
detect-rounded-corners = false

mark-wmwin-focused = true
mark-overdir-focused = true
detect-client-opacity = true
detect-transistent = true
detect-client-leader = true
use-ewmh-active-win = true

rounded-corners-exclude = [
	"class_g = 'Eww'"
]
