backend = "glx"
vsync = true
sw-opti = false
use-damage = false
frame-pacing = true
xrender-sync-fence = false
unredir-if-possible = false
glx-copy-from-font = false

corner-radius = 24
round-borders = 24
paint-on-overlay = true
detect-rounded-corners = false

mark-wmwin-focused = true
mark-overdir-focused = true
detect-client-opacity = true
detect-transistent = true
detect-client-leader = true
use-ewmh-active-win = true

rounded-corners-exclude = [
	"class_g = 'Eww'",
	"class_g = 'Rofi'"
]

corner-radius-rules = [
  	"12:window_type = 'menu'",
	"12:window_type = 'dropdown_menu'",
  	"12:window_type = 'popup_menu'",
	"18:window_type = 'dialog'"
];
