[DEFAULT]
fetch-updates-in-background = no

[app.df8a8ce2825716efdba1cf0564262ac4]
website = 
name = QDiskInfo
file_path = /home/aKqir24/Desktop/.AppImages/qdiskinfo.appimage

[app.f6be7bd2a9b7b65f95ec7293865a13c5]
website = 
name = GNU Image Manipulation Program
file_path = /home/aKqir24/Desktop/.AppImages/gnu_image_manipulation_program.appimage

[app.064add5a9a66fe09f59297b34c407973]
website = 
name = rustdesk
file_path = /home/aKqir24/Desktop/.AppImages/rustdesk.appimage

[app.6d64ad7341162f9632525e4547ffc350]
name = drawio
file_path = /home/aKqir24/Desktop/.AppImages/drawio.appimage

[app.51e449bbebf17c9d8f2c09d9daa4fd60]
name = figma-linux
file_path = /home/aKqir24/Desktop/.AppImages/figmalinux.appimage

[app.18ce90a19a14b740e84f2ebdab623b4d]
name = LibreOffice
file_path = /home/aKqir24/Desktop/.AppImages/libreoffice.appimage

[app.48ee3ade1ae784398deab4e186afc88e]
name = Figma
file_path = /home/aKqir24/Desktop/.AppImages/figma.appimage

[app.92283a468bc3c0d580f78fc9b730f129]
name = Shotcut
file_path = /home/aKqir24/Desktop/.AppImages/shotcut.appimage

[app.698c9c0284496d3493a2682f08767582]
name = Inkscape
file_path = /home/aKqir24/Desktop/.AppImages/inkscape.appimage

[app.48ee3ade1ae784398deab4e186afc88e.update_manager]

[app.47779e41083974aef6aae02ce605572e]
name = VSCodium
file_path = /home/aKqir24/Desktop/.AppImages/vscodium.appimage

[app.2d5a42bdb34c61b117c2a24c7c024a6f]
name = OpenCode
file_path = /home/aKqir24/AppImages/opencode.appimage

[app.2d5a42bdb34c61b117c2a24c7c024a6f.update_manager]

[app.8030619b23f9d6c0cd5b721cb2cc5552]
default_exec_arguments = %f
name = LMMS
file_path = /home/aKqir24/Desktop/.AppImages/lmms.appimage

[app.8030619b23f9d6c0cd5b721cb2cc5552.update_manager]

[app.e24c4fed6b640b0629dc1a1330d52adb]
default_exec_arguments = %u
name = Zen Browser
file_path = /home/aKqir24/Desktop/.AppImages/zen_browser.appimage_1_21_11b.appimage

[app.e24c4fed6b640b0629dc1a1330d52adb.update_manager]

[app.2ae3b7852d12d9e44deaead35b38b0c9]
default_exec_arguments = %u
name = Zen Browser
file_path = /home/aKqir24/Desktop/.AppImages/zen_browser.appimage

[app.941e38ce435118ba616b03569a055689]
default_exec_arguments = 
name = OBS Studio
file_path = /home/aKqir24/Desktop/.AppImages/obs_studio.appimage

[app.18ce90a19a14b740e84f2ebdab623b4d.update_manager]

[app.6d64ad7341162f9632525e4547ffc350.update_manager]

[app.82c797b80646127b175c36b1986a32e8]
default_exec_arguments = %U
name = Audacity 4 Portable
file_path = /home/aKqir24/Desktop/.AppImages/audacity_4_portable.appimage

[app.6301ce752daee36b11499ef1311b263f.update_manager]

