[colors.normal]
red = "#6165D6"
cyan = "#F8D9A9"
green = "#B765A9"
white = "#9897a0"
black = "#191236"
blue = "#5A96DE"
magenta = "#F3999C"
yellow = "#9A6FE3"

[colors.line_indicator]
background = "None"
foreground = "None"

[colors.selection]
background = "CellForeground"
text = "CellBackground"

[colors.footer_bar]
foreground = "#c5c3cc"
background = "#9897a0"

[colors.bright]
black = "#69647b"
red = "#9598d2"
green = "#cc87bf"
blue = "#96b1d2"
cyan = "#e9decd"
magenta = "#e5c2c3"
white = "#c5c3cc"
yellow = "#b7a4d8"

[colors.primary]
background = "#191236"
foreground = "#c5c3cc"

[colors.cursor]
text = "#191236"
cursor = "#9897a0"

[colors.vi_mode_cursor]
text = "#191236"
cursor = "#c5c3cc"

[colors.search.matches]
foreground = "#191236"
background = "#c5c3cc"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[window.padding]
x = 12
y = 12

[font]
size = 12

[font.normal]
family = "EnvyCodeR Nerd Font Mono"

[font.bold]
family = "EnvyCodeR Nerd Font"
style = "Regular"
