[colors.normal]
red = "#81735C"
cyan = "#CFB697"
green = "#C96D4A"
white = "#9a9690"
black = "#1e170d"
blue = "#E08964"
magenta = "#AFA287"
yellow = "#E3815B"

[colors.line_indicator]
background = "None"
foreground = "None"

[colors.selection]
background = "CellForeground"
text = "CellBackground"

[colors.footer_bar]
foreground = "#c6c5c2"
background = "#9a9690"

[colors.bright]
black = "#70695c"
red = "#bd9e66"
green = "#c99683"
blue = "#d4ad9c"
cyan = "#dcc8af"
magenta = "#d2be95"
white = "#c6c5c2"
yellow = "#d3aa9a"

[colors.primary]
background = "#1e170d"
foreground = "#c6c5c2"

[colors.cursor]
text = "#1e170d"
cursor = "#9a9690"

[colors.vi_mode_cursor]
text = "#1e170d"
cursor = "#c6c5c2"

[colors.search.matches]
foreground = "#1e170d"
background = "#c6c5c2"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[window.padding]
x = 12
y = 12

[font]
size = 12

[font.normal]
family = "EnvyCodeR Nerd Font Mono"

[font.bold]
family = "EnvyCodeR Nerd Font"
style = "Regular"
