#!/bin/bash
:wqpkill -f "yboard-handler" 2>/dev/null
if eww active-windows 2>/dev/null | grep -q launcher; then
    eww close launcher
else
    eww update search_query=""
    ~/.config/eww/scripts/search-apps.sh ""
    eww open launcher
    ~/.config/eww/scripts/keyboard-handler &
fi
